name: PHP CS Fixer

on:
  workflow_call:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP CS Fixer - PHP 8.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: php-cs-fixer, cs2pr

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix -v --dry-run --using-cache=no --format=checkstyle | cs2pr