name: Tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']
    uses: ./.github/workflows/reusable/phpunit.yml
    with:
      php-version: ${{ matrix.php-version }}